version: '3.8'
services:
  oxygen:
    image: ghcr.io/oxygenpay/oxygen:latest
    command: all-in-one --skip-config
    env_file:
      - docker.env
    volumes:
      - './tmp:/src/tmp'
    ports: [ '80:80' ]
    networks: [ net-oxygen ]
    depends_on: [ postgres ]
    restart: on-failure

  postgres:
    image: postgres:15-alpine
    command: postgres -c log_statement=all
    restart: on-failure
    environment:
      - POSTGRES_DB=oxygen
      - POSTGRES_USER=oxygen
      - POSTGRES_PASSWORD=oxygen
    volumes:
      - 'pg-data:/var/lib/postgresql/data'
    ports: [ '5432:5432' ]
    networks: [ net-oxygen ]

networks:
  net-oxygen:

volumes:
  app-volume:
  pg-data:
